Repository earthhistoryviz/tsconline, pull requests merged in 2024-07, with the labels that each got.

#145 finished adding tests for login routes
  .pnp.cjs
  .yarn/cache/@esbuild-linux-x64-npm-0.20.2-54b0127370-10.zip
  .yarn/cache/@esbuild-linux-x64-npm-0.21.5-88079726c4-10.zip
  .yarn/cache/@esbuild-win32-x64-npm-0.20.2-4f45bbb49b-10.zip
  .yarn/cache/@esbuild-win32-x64-npm-0.21.5-eddc2b5ad6-10.zip
  .yarn/cache/@rollup-rollup-linux-x64-gnu-npm-4.17.2-0d17f6c4a4-10.zip
  .yarn/cache/@rollup-rollup-win32-x64-msvc-npm-4.17.2-36fa45f655-10.zip
  .yarn/cache/form-auto-content-npm-3.2.1-e8f19b4819-dea1635e47.zip
  .yarn/cache/mkdirp-npm-3.0.1-f94bfa769e-16fd79c286.zip
  app/src/Profile.tsx
  app/src/state/actions/general-actions.ts
  app/src/state/state.ts
  app/src/types.ts
  app/src/util/error-codes.ts
  package.json
  server/__tests__/login-routes.test.ts
  server/package.json
  server/src/index.ts
  server/src/login-routes.ts
  server/src/routes.ts
  server/src/types.ts
  shared/src/index.ts
  yarn.lock
Labels: tests

#160 Small tweaks and changes to ui
  app/src/ChartOptionsBar.tsx
  app/src/components/datapack_display/TSCCompactDatapackRow.module.css
  app/src/components/datapack_display/TSCCompactDatapackRow.tsx
  app/src/settings_tabs/Datapack.tsx
  app/src/settings_tabs/LoadSettings.tsx
  app/src/settings_tabs/SaveSettings.tsx
  app/src/state/state.ts
Labels: enhancement

#156 routes to admin delete, create, display user, delete user datapacks, add/delete server datapacks
  .eslintrc.json
  .yarn/cache/@esbuild-win32-x64-npm-0.20.2-4f45bbb49b-10.zip
  .yarn/cache/@esbuild-win32-x64-npm-0.21.5-eddc2b5ad6-10.zip
  .yarn/cache/@rollup-rollup-win32-x64-msvc-npm-4.17.2-36fa45f655-10.zip
  app/src/state/actions/general-actions.ts
  server/__tests__/admin-routes.test.ts
  server/__tests__/login-routes.test.ts
  server/assets/.gitignore
  server/assets/config.json
  server/db/migrations/2024.07.02-02.12.34-add-admin.ts
  server/package.json
  server/src/admin-auth.ts
  server/src/admin-routes.ts
  server/src/database.ts
  server/src/file-metadata-handler.ts
  server/src/index.ts
  server/src/load-packs.ts
  server/src/login-routes.ts
  server/src/routes.ts
  server/src/types.ts
  server/src/util.ts
Labels: enhancement

#163 update config file
  server/assets/config.json
Labels: bug

#166 tests for admin upload configure datapacks and getting users
  server/__tests__/admin-routes.test.ts
  server/src/admin-routes.ts
Labels: tests

#170 fixed incorrect calculation of points for map points
  app/src/util/coordinates.ts
Labels: bug

#173 Tsc 444 fix parse settings tests
  app/__tests__/__data__/parse-settings-keys.json
  app/__tests__/__data__/parse-settings-tests.json
  app/__tests__/parse-settings.test.ts
  server/__tests__/__data__/column-keys.json
  server/__tests__/parse-datapacks.test.ts
  server/src/parse-datapacks.ts
Labels: tests

#176 Temp branch for svg realpath fix
  app/src/ChartOptionsBar.tsx
  app/src/components/TSCButton.tsx
  server/src/routes.ts
Labels: enhancement

#177 Tsc 431 pr puts up a server
  .github/workflows/cleanup-preview.yml
  .github/workflows/codeql-pipeline.yml
  .github/workflows/deploy-preview.yml
  .github/workflows/merge-pipeline.yml
  .gitignore
  deploy.sh
  docker-compose-preview.yml
  docker-compose.yml
Labels: enhancement

#175 Tsc 413 download chart as png pdf make dialog focus on mount
  app/package.json
  app/src/ChartOptionsBar.tsx
  app/src/components/TSCLoadingButton.tsx
  app/src/settings_tabs/Search.tsx
  app/src/state/actions/general-actions.ts
  app/src/state/state.ts
  app/src/types.ts
  app/src/util/workers/download-pdf.ts
  app/vite.config.ts
  yarn.lock
Labels: enhancement

#180 Tsc 442 front end for admin
  app/package.json
  app/src/App.tsx
  app/src/NavBar.tsx
  app/src/account_settings/AccountMenu.tsx
  app/src/account_settings/Profile.css
  app/src/account_settings/Profile.tsx
  app/src/admin/Admin.css
  app/src/admin/Admin.tsx
  app/src/admin/AdminAddUserForm.tsx
  app/src/admin/AdminDatapackConfig.tsx
  app/src/admin/AdminUserConfig.tsx
  app/src/admin/UnauthorizedAccess.module.css
  app/src/admin/UnauthorizedAccess.tsx
  app/src/assets/icons/smartphone-lock.json
  app/src/components/TSCCustomTabs.tsx
  app/src/components/datapack_display/TSCCompactDatapackRow.tsx
  app/src/components/index.ts
  app/src/settings_tabs/Datapack.tsx
  app/src/settings_tabs/column_menu/ColumnMenu.tsx
  app/src/state/actions/admin-actions.ts
  app/src/state/actions/index.ts
  app/src/state/actions/util-actions.ts
  app/src/state/state.ts
  app/src/theme.ts
  app/src/util.ts
  app/src/util/error-codes.ts
  server/__tests__/admin-routes.test.ts
  server/db/migrations/2024.05.08-17.59.45-adjust-columns-in-verification-table.ts
  server/src/admin-auth.ts
  server/src/admin-routes.ts
  server/src/database.ts
  server/src/index.ts
  server/src/login-routes.ts
  shared/src/index.ts
  yarn.lock
Labels: enhancement

#181 Tsc 446 event search new perspective
  app/package.json
  app/src/settings_tabs/Results.css
  app/src/settings_tabs/Results.tsx
  app/src/settings_tabs/Search.css
  app/src/settings_tabs/Search.tsx
  app/src/types.ts
  yarn.lock
Labels: enhancement

#187 fix for polarity clear
  app/src/state/actions/column-actions.ts
Labels: enhancement

#186 Tsc 447 admin datapack config frontend
  app/src/admin/Admin.tsx
  app/src/admin/AdminDatapackConfig.tsx
  app/src/admin/AdminUserConfig.tsx
  app/src/components/datapack_display/TSCDatapackUploadForm.tsx
  app/src/settings_tabs/Datapack.tsx
  app/src/state/actions/admin-actions.ts
  app/src/state/actions/general-actions.ts
  app/src/state/state.ts
  app/src/util/error-codes.ts
  server/__tests__/__data__/column-keys.json
  server/__tests__/admin-routes.test.ts
  server/src/admin-auth.ts
  server/src/admin-routes.ts
  server/src/index.ts
  server/src/load-packs.ts
  server/src/parse-datapacks.ts
  server/src/routes.ts
  server/src/types.ts
  server/src/util.ts
  shared/src/index.ts
Labels: enhancement

#190 added priority to queue for logged in users
  server/src/index.ts
  server/src/routes.ts
Labels: enhancement

#205 Tsc 467 make deploy actions listen to docker logs to return errors properly
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-preview.yml
  .github/workflows/deploy-release.yml
  .github/workflows/merge-pipeline.yml
Labels: enhancement

#193 Tsc 408 read settings must support data mining columns
  app/src/state/actions/column-actions.ts
  app/src/state/actions/general-actions.ts
  app/src/state/parse-settings.ts
  server/src/parse-datapacks.ts
Labels: enhancement
